data:
  requests_cpu: "0.1"
  requests_memory: "260M"
  limits_cpu: "1"
  limits_memory: "1G"
  serviceAccountName: "partition"
  imagePullPolicy: "IfNotPresent"
  image: ""
  # bootstrap common
  bootstrap_limits_cpu: "0.1"
  bootstrap_limits_memory: "200M"
  bootstrap_image: ""
  bootstrapServiceAccountName: "partition-bootstrap"
conf:
  configmap: "partition-config"
  secret: "partition-postgres-secret"
  app_name: "partition"
  # bootstrap common
  bootstrap_name: "partition-bootstrap"
  bootstrap_configmap: "partition-bootstrap-configmap"
  bootstrap_namespace: "default"
  on_prem_enabled: false
namespacePolicy:
  mtlsMode: STRICT
authorizations:
  partitionPolicy:
    matchLabels:
      app: partition
    rules:
      - bootstrap_namespace: config
