variables:
  OSDU_GCP_ENABLE_BOOTSTRAP: "true"
  OSDU_GCP_SERVICE: partition
  OSDU_GCP_VENDOR: gcp

osdu-gcp-test:
  variables:
    CLIENT_TENANT: osdu

osdu-gcp-dev2-test:
  variables:
    CLIENT_TENANT: devtwo

osdu-gcp-anthos-test:
  variables:
    OSDU_GCP_VENDOR: anthos
