apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.conf.configmap }}"
data:
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  JAVA_APP_JAR: "{{ .Values.data.javaAppJar }}"
  server.servlet.context-path: "{{ .Values.data.contextPath }}"
  server.port: "{{ .Values.data.serverPort }}"
  spring.main.allow-bean-definition-overriding: "{{ .Values.data.beanDefOverriding }}"
  ACCEPT_HTTP: "{{ .Values.data.acceptHttp }}"
  keycloak.auth-server-url: "http://keycloak-discovery:8080/auth"
  keycloak.credentials.secret: "{{ .Values.data.keycloakClientSecret }}"
  service.partition.admin.user: "{{ .Values.data.svcPartionAdminUser }}"
  LOG_PREFIX: "{{ .Values.data.logPrefix }}"
  cache.expiration: "{{ .Values.data.cacheExpiration }}"
  cache.maxSize: "{{ .Values.data.cahceMaxSize }}"
  ibm.health-check-uri: "{{ .Values.data.healthCheckUri }}"
  logging.level.org.opengroup.osdu: "{{ .Values.data.loggingLevelOsdu }}"
  logging.level.org.springframework.web: "{{ .Values.data.loggingLevelSpring }}"
  AUTHORIZE_API: "{{ .Values.data.authorizeAPI }}"
  DEPLOYMENT_ENVIRONMENT: "{{ .Values.data.deployEnv }}"
  ibm.db.url: "http://{{ .Release.Name }}-couchdb:5984"
  ibm.db.user: "{{ .Values.data.dbUser }}"
  ibm.env.prefix: "{{ .Values.data.envPrefix }}"
  ibm.env.prefix_project: "{{ .Values.data.envPrefixProject }}"
  ibm.keycloak.endpoint_url: "keycloak-discovery:8080"
  ibm.keycloak.realm: "{{ .Values.data.keycloakRealm }}"
  ibm.keycloak.useremail: "{{ .Values.data.keycloakUserEmail }}"
  ibm.db.password: "{{ .Values.data.dbPassw }}"
  PARTITION_API: "{{ .Values.data.patitionAPI }}"
  POLICY_API: "{{ .Values.data.policyAPI }}"
  partition.keycloak.client_id: "{{ .Values.data.kcClientId }}"
  partition.keycloak.client_secert: "{{ .Values.data.keycloakClientSecret }}"
  partition.keycloak.grant_type: "{{ .Values.data.grantType }}"
  partition.keycloak.password: "{{ .Values.data.kcPassword }}"
  partition.keycloak.realm: "{{ .Values.data.keycloakRealm }}"
  partition.keycloak.url: "{{ .Values.data.keycloakEndPointHost }}"
  partition.keycloak.user: "{{ .Values.data.kcUser }}"
  tenantCache.exp.time.in.second: "{{ .Values.data.tenantCacheExpiryInSec }}"
  osdu.airflow.url: "http://{{ .Release.Name }}-web:8080"
  pipline.trigger.url: "http://{{ .Release.Name }}-ibm-indexer-queue-deploy:8080"
