apiVersion: v1
data:
  AUTHORIZE_API: ${AUTHORIZE_API}
  MONGO_DB_URL: ${MONGO_DB_URL}
  MONGO_DB_USER: ${MONGO_DB_USER}
  MONGO_DB_NAME: ${MONGO_DB_NAME}
  GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
  GOOGLE_AUDIENCES: ${GOOGLE_AUDIENCES}
  KEY_RING: ${KEY_RING}
  KMS_KEY: ${KMS_KEY}
  PARTITION_ADMIN_ACCOUNTS: ${PARTITION_ADMIN_ACCOUNTS}
  LOG_LEVEL: ${LOG_LEVEL}

kind: ConfigMap
metadata:
  labels:
    app: partition-reference
  name: partition-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: partition-reference-anthos
  labels:
    app: partition-reference
  name: partition-reference
  namespace: default
spec:
  selector:
    matchLabels:
      app: partition-reference
  replicas: 1
  template:
    metadata:
      labels:
        app: partition-reference
    spec:
      containers:
        -   env:
              -   name: AUTHORIZE_API
                  valueFrom:
                    configMapKeyRef:
                      key: AUTHORIZE_API
                      name: partition-config
              - name: PARTITION_ADMIN_ACCOUNTS
                  valueFrom:
                    configMapKeyRef:
                      key: PARTITION_ADMIN_ACCOUNTS
                      name: partition-config
              - name: LOG_LEVEL
                  valueFrom:
                    configMapKeyRef:
                      key: LOG_LEVEL
                      name: partition-config
              -   name: MONGO_DB_URL
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_URL
                      name: partition-config
              -   name: MONGO_DB_USER
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_USER
                      name: partition-config
              -   name: MONGO_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: partition-secret
                      key: mongo.db.password
              -   name: MONGO_DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_NAME
                      name: partition-config
              -   name: GOOGLE_CLOUD_PROJECT
                  valueFrom:
                    configMapKeyRef:
                      key: GOOGLE_CLOUD_PROJECT
                      name: partition-config
              -   name: GOOGLE_AUDIENCES
                  valueFrom:
                    configMapKeyRef:
                      key: GOOGLE_AUDIENCES
                      name: partition-config
              -   name: KEY_RING
                  valueFrom:
                    configMapKeyRef:
                      key: KEY_RING
                      name: partition-config
              -   name: KMS_KEY
                  valueFrom:
                    configMapKeyRef:
                      key: KMS_KEY
                      name: partition-config
            image: us.gcr.io/osdu-anthos-02/os-partition/anthos-partition-reference:9966597-dirty
            name: partition-reference
---
apiVersion: v1
kind: Service
metadata:
  name: partition-reference
  namespace: default
spec:
  ports:
    -   protocol: TCP
        port: 80
        targetPort: 8080
  selector:
    app: partition-reference
  type: LoadBalancer
---
apiVersion: v1
data:
  mongo.db.password: ${mongo.db.password}
kind: Secret
metadata:
  name: partition-secret
  namespace: default
type: Opaque