apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-partition-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-partition-master
  template:
    metadata:
      name: redis-partition-master
      labels:
        app: redis-partition-master
        master: "true"
    spec:
      volumes:
      - hostPath:
          path: /tmp/data/1
        name: redis-directory-binding

      restartPolicy: Always

      containers:
        - name: redis-partition-master
          image: delfi.azurecr.io/redis-partition-cluster:latest

          resources:
            requests:
              memory: "100Mi"
              cpu: .2
            limits:
              memory: "200Mi"
              cpu: .5

          imagePullPolicy: Always

          ports:
          - containerPort: 6379

          volumeMounts:
          - mountPath: /redis-data
            name: redis-directory-binding
            readOnly: false

          env:
          - name: MASTER
            value: "true"
      imagePullSecrets:
        - name: acr