variables:
  GC_QUARKUS_SERVICE: partition-quarkus
  GC_QUARKUS_NAMESPACE: "partition-quarkus-int-test"
  GC_QUARKUS_HELM_DIR: "devops/gc-quarkus/deploy"
  GC_QUARKUS_HELM_PACKAGE_NAME: "gc-partition-quarkus-deploy"

gc-quarkus-compile-and-unit-test:
  extends:
    - .gc-variables
  stage: csp-build
  needs: ["compile-and-unit-test"]
  image: maven:3.9.3-eclipse-temurin-17
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  before_script:
    - "mkdir -p .m2/repository"
  script:
    - cd provider/partition-gc-quarkus
    - mvn clean package
  artifacts:
    paths:
      - provider/partition-gc-quarkus/target/quarkus-app/
  rules:
    - if: $GC == "1"
      when: on_success

gc-quarkus-containerize-gitlab:
  extends: gc-containerize-gitlab
  stage: containerize
  needs: ["gc-quarkus-compile-and-unit-test"]
  variables:
    GC_SERVICE: $GC_QUARKUS_SERVICE
    GC_VENDOR: gc-quarkus
    BUILD_PATH: provider/partition-gc-quarkus/cloudbuild/Dockerfile.cloudbuild
  rules:
    - if: $GC == "1"
      when: on_success

gc-quarkus-helm-charts-gitlab:
  extends: gc-helm-charts-gitlab
  needs: ["gc-quarkus-containerize-gitlab"]
  variables:
    GC_HELM_DEPLOYMENT_DIR: $GC_QUARKUS_HELM_DIR
    GC_HELM_PACKAGE_NAME: $GC_QUARKUS_HELM_PACKAGE_NAME
    GC_SERVICE: $GC_QUARKUS_SERVICE

gc-quarkus-deploy:
  extends: gc-deploy
  needs: ["gc-quarkus-helm-charts-gitlab"]
  variables:
    GC_HELM_DIR: $GC_QUARKUS_HELM_DIR
    GC_SERVICE: $GC_QUARKUS_SERVICE
    GC_HELM_PACKAGE_NAME: $GC_QUARKUS_HELM_PACKAGE_NAME
    GC_ENABLE_BOOTSTRAP: "false"
    GC_HELM_SETS: "--set data.serviceAccountName=partition"

gc-quarkus-test:
  extends:
    - .gc-variables
    - .maven
  stage: integration
  needs: ["gc-quarkus-deploy"]
  variables:
    CLIENT_TENANT: test
    PARTITION_BASE_URL: https://community.gcp.gnrg-osdu.projects.epam.com/api/partition-quarkus/v1
  script:
    - cd provider/partition-gc
    - mvn test -Dtest=*IT -DfailIfNoTests=false
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^release/"
      when: never
    - if: "$CI_COMMIT_TAG"
      when: never
    - if: '$GC == "1" && $GC_INT_TEST_TYPE != "python"'
      when: on_success

gc-quarkus-helm-charts-release-gitlab:
  extends: gc-helm-charts-release-gitlab
  needs: ["gc-quarkus-containerize-gitlab"]
  variables:
    GC_HELM_DEPLOYMENT_DIR: $GC_QUARKUS_HELM_DIR
    GC_HELM_PACKAGE_NAME: $GC_QUARKUS_HELM_PACKAGE_NAME
    GC_SERVICE: $GC_QUARKUS_SERVICE

gc-quarkus-helm-charts-release-gcr:
  extends: gc-helm-charts-release-gcr
  needs: ["gc-quarkus-containerize-gitlab"]
  variables:
    GC_HELM_DEPLOYMENT_DIR: $GC_QUARKUS_HELM_DIR
    GC_HELM_PACKAGE_NAME: $GC_QUARKUS_HELM_PACKAGE_NAME
    GC_SERVICE: $GC_QUARKUS_SERVICE

gc-quarkus-dev2-deploy:
  extends: gc-dev2-deploy
  needs: ["gc-quarkus-helm-charts-release-gitlab"]
  variables:
    GC_HELM_DIR: $GC_QUARKUS_HELM_DIR
    GC_SERVICE: $GC_QUARKUS_SERVICE
    GC_HELM_PACKAGE_NAME: $GC_QUARKUS_HELM_PACKAGE_NAME
    GC_ENABLE_BOOTSTRAP: "false"
    GC_HELM_SETS: "--set data.serviceAccountName=partition"
