global:
  domain: ""
  useHttps: true
  onPremEnabled: false
  limitsEnabled: true
  dataPartitionId: ""
  logLevel: "ERROR"
  tier: ""
  autoscaling: true

data:
  # configmaps
  logLevel: ""
  projectId: ""
  dataProjectId: ""
  partitionHost: "partition"
  partitionNamespace: "partition"
  partitionSuffix: "_SYSTEM"
  datafierSa: "datafier"
  bucketPrefix: "refi"
  minioExternalEndpoint: "" # use only if external minio is configured
  minioIgnoreCertCheck: "false"
  indexerAugmenterEnabled: "false"
  policyServiceEnabled: "true"
  edsEnabled: "false"
  minioUIEndpoint: "http://minio:9001"
  autocompleteEnabled: "false"
  # deployments
  requestsCpu: "5m"
  requestsMemory: "350Mi"
  limitsCpu: "500m"
  limitsMemory: "1G"
  serviceAccountName: "partition"
  imagePullPolicy: "IfNotPresent"
  image: "community.opengroup.org:5555/osdu/platform/system/partition/osdu-gcp-partition:latest"
  bootstrapImage: "community.opengroup.org:5555/osdu/platform/system/partition/osdu-gcp-bootstrap-partition:latest"
  # bootstrap onprem

conf:
  appName: "partition"
  configmap: "partition-config"
  secret: "partition-postgres-secret"
  replicas: 2

auth:
  realm: "osdu"

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "5m"
  bootstrapProxyCPULimit: "100m"
  sidecarInject: "true"
  partitionEditors: []

hpa:
  minReplicas: 6
  maxReplicas: 15
  targetType: "AverageValue" #Could be AverageValue or Value
  targetValue: 400 #200 rps
  behaviorScaleUpStabilizationWindowSeconds: 10
  behaviorScaleUpPoliciesValue: 50
  behaviorScaleUpPoliciesPeriodSeconds: 15
  behaviorScaleDownStabilizationWindowSeconds: 60
  behaviorScaleDownPoliciesValue: 25
  behaviorScaleDownPoliciesPeriodSeconds: 60

limits:
  maxTokens: 250
  tokensPerFill: 250
  fillInterval: "1s"
