global:
  domain: ""
  useHttps: true
  limitsEnabled: true
  dataPartitionId: ""
  logLevel: "ERROR"

data:
  # configmaps
  logLevel: ""
  projectId: ""
  dataProjectId: ""
  partitionHost: "partition"
  partitionNamespace: "partition"
  partitionSuffix: "_SYSTEM"
  datafierSa: "datafier"
  bucketPrefix: "refi"
  indexerAugmenterEnabled: "false"
  policyServiceEnabled: "true"
  edsEnabled: "false"
  autocompleteEnabled: "false"
  # deployments
  requestsCpu: "5m"
  requestsMemory: "350Mi"
  limitsCpu: "500m"
  limitsMemory: "1G"
  serviceAccountName: "partition"
  imagePullPolicy: "IfNotPresent"
  image: "community.opengroup.org:5555/osdu/platform/system/partition/osdu-gcp-partition:latest"
  bootstrapImage: "community.opengroup.org:5555/osdu/platform/system/partition/osdu-gcp-bootstrap-partition:latest"

conf:
  appName: "partition"
  configmap: "partition-config"
  secret: "partition-postgres-secret"
  replicas: 2

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "5m"
  bootstrapProxyCPULimit: "100m"
  sidecarInject: "true"
  partitionEditors: []
