{{- template "common.authzpolicy" (list . "os-partition.authzpolicy") -}}
{{- define "os-partition.authzpolicy" -}}
## Define overrides for the service authorization policy resource here
{{- end -}}

