{{- template "common.destinationrule" (list . "os-partition.destinationrule") -}}
{{- define "os-partition.destinationrule" -}}
## Define overrides for the service destination rule resource here
{{- end -}}