{{- template "common.serviceaccount" (list . "os-partition.serviceaccount") -}}
{{- define "os-partition.serviceaccount" -}}
## Define overrides for the service's service account resource here
{{- end -}}