apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.data.serviceAccountName | quote }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-bootstrap" .Values.data.serviceAccountName | quote }}
  namespace: {{ .Release.Namespace | quote }}
