variables:
  CORE_SERVICE: partition
  CORE_ENABLE_BOOTSTRAP: "true"
  CORE_BUILD_BOOTSTRAP_PATH: "devops/core-plus/bootstrap/Dockerfile"

core-deploy:
  variables:
    CORE_HELM_SETS: >-
      --set data.elasticHttps=false

core-test:
  variables:
    #required for integration tests
    PARTITION_BASE_URL: https://osdu.core-dev.gcp.gnrg-osdu.projects.epam.com/

  script:
    $MAVEN_BUILD . test-results.log
      verify -DdisableXmlReport=true
      --file testing/pom.xml
      --projects partition-test-core,partition-test-core-plus
      --update-snapshots
