apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.data.springProfilesActive | quote }}
  {{- if not .Values.conf.onPremEnabled }}
  GOOGLE_CLOUD_PROJECT: {{ .Values.data.projectId | quote }}
  PARTITION_NAMESPACE: {{ .Values.data.partitionNamespace | quote }}
  {{- end }}
