{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ibm-partition-deploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ibm-partition-deploy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-40"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ibm-partition-deploy.serviceAccountName" . }}
  labels:
    {{- include "ibm-partition-deploy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-40"
rules:
  - apiGroups:
      - "config.openshift.io"
      - "security.istio.io"
      - "networking.istio.io"
      - ""
      - "broker.amq.io"
      - "batch"
    resources:
      - "secrets"
      - "configmaps"
      - "services"
      - "requestauthentications"
      - "envoyfilters"
      - "activemqartemises"
      - "jobs"
    verbs:
      - "list"
      - "get"
      - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ibm-partition-deploy.serviceAccountName" . }}
  labels:
    {{- include "ibm-partition-deploy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-40"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ibm-partition-deploy.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ibm-partition-deploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
