apiVersion: v1
data:
  configMap_update_script.sh: |
    {{- tpl (.Files.Get "files/configMap_update_script.sh" ) . | nindent 4 }}
kind: ConfigMap
metadata:
  name: update-script-configmap
  labels:
    {{- include "ibm-partition-deploy.labels" . | nindent 4 }}
