variables:
  SERVICE_PORT: 8080
  POSTGRES_DATASOURCE_URL_OSDU: jdbc:postgresql://172.17.0.2:5432/postgres
  POSTGRES_DB_USERNAME_OSDU: postgres
  POSTGRES_DB_PASSWORD_OSDU: $GC_OSM_POSTGRES_PASSWORD
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: $GC_OSM_POSTGRES_PASSWORD
  TEST_OPENID_PROVIDER_CLIENT_ID: integration-tester
  TEST_OPENID_PROVIDER_CLIENT_SECRET: $GC_OPENID_PROVIDER_CLIENT_SECRET
  TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_ID: no-access-tester
  TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_SECRET: $GC_NO_ACCESS_OPENID_PROVIDER_CLIENT_SECRET
  TEST_OPENID_PROVIDER_URL: https://keycloak.ref.gcp.gnrg-osdu.projects.epam.com/realms/osdu

core-plus-containerize:
  stage: containerize
  needs: ["compile-and-unit-test"]
  tags: ["osdu-small"]
  image: docker:19.03
  cache: {}
  variables:
    BUILD_ARGS: "--build-arg PORT=$SERVICE_PORT"
    BUILD_PATH: "devops/core-plus/build/Dockerfile"
    CUSTOM_PROJECT_NAME: "partition-core-plus"
    IMAGE_NAME: ${CUSTOM_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
  script:
    - echo building $CI_REGISTRY_IMAGE:$IMAGE_NAME
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME -f $BUILD_PATH $BUILD_ARGS .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME
  only:
    variables:
      - $PROTECTED == '1'

core-plus-tests:
  tags: [ "osdu-medium" ]
  extends:
    - .maven
  stage: integration
  needs: [ "compile-and-unit-test", "core-plus-containerize" ]
  retry: 1
  services:
    - name: postgres
      command:
        ["postgres", "-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    - name: docker:dind #necessary for docker-run
  variables:
    FF_NETWORK_PER_BUILD: "true"     # activate container-to-container networking
    PARTITION_POSTGRESQL_DB_NAME: partition_db
    PARTITION_POSTGRESQL_USERNAME: usr_partition_pg
    PARTITION_POSTGRESQL_PASSWORD: partition_pg
    POSTGRESQL_PORT: 5432
    POSTGRESQL_HOST: postgres
    POSTGRESQL_USERNAME: postgres
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRESQL_DATABASE: postgres
    POSTGRESQL_PASSWORD: $POSTGRES_PASSWORD
    TEST_OPENID_PROVIDER_CLIENT_ID: integration-tester
    TEST_OPENID_PROVIDER_CLIENT_SECRET: $GC_OPENID_PROVIDER_CLIENT_SECRET
    TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_ID: no-access-tester
    TEST_NO_ACCESS_OPENID_PROVIDER_CLIENT_SECRET: $GC_NO_ACCESS_OPENID_PROVIDER_CLIENT_SECRET
    TEST_OPENID_PROVIDER_URL: https://keycloak.ref.gcp.gnrg-osdu.projects.epam.com/realms/osdu
    DATA_PARTITION_ID: test-partition
    CUSTOM_PROJECT_NAME: "partition-core-plus"
    #required for integration tests
    CLIENT_TENANT: osdu
    ENVIRONMENT: dev #if this is not specified, it just assumes that the service is running locally
    PARTITION_BASE_URL: http://PartitionService:8080/
    CI_DEBUG_SERVICES: "true"
  script:
    - docker run -d --name PartitionService -p 8080:8080 ${CI_REGISTRY_IMAGE}/${CUSTOM_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
    - sleep 30 #wait for the service to come up, TODO, add another way here
    - echo "--- Install psql ---"
    - apt-get update && apt-get install -y postgresql-client libpq-dev jq
    - echo "--- Bootstrap tables ---"
    - chmod +x devops/core-plus/test/bootstrap.sh
    - devops/core-plus/test/bootstrap.sh
    - curl "http://PartitionService:8080" #check service is reachable
    - echo "--- Run integration tests ---"
    - >
      $MAVEN_BUILD . test-results.log
      verify -DdisableXmlReport=true
      --quiet
      --file testing/pom.xml
      --projects partition-test-core,partition-test-core-plus
      --update-snapshots
  artifacts:
    when: always
    paths:
      - test-results.log
    expire_in: 1 days
  only:
    variables:
      - $PROTECTED == '1'
