version: "3"
services:
  os-storage-app:
    build:
      args: 
        JAR_FILE: target/partition-reference-0.12.0-spring-boot.jar
      context: ""
      dockerfile: ../Dockerfile
    image: us.gcr.io/osdu-anthos-02/os-partition/anthos-partition-reference
    ports:
     - "8080:8080"

