apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.conf.app_name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.conf.app_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.conf.app_name }}"
    spec:
      containers:
        - image: "{{ .Values.data.image }}"
          imagePullPolicy: Always
          name: "{{ .Values.conf.app_name }}"
          env:
            - name: "ACCEPT_HTTP"
              value: "true"
          envFrom:
          - configMapRef:
              name: "{{ .Values.conf.configmap }}"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "{{ .Values.data.requests_cpu }}"
              memory: "{{ .Values.data.requests_memory }}"
            limits:
              cpu: "{{ .Values.data.limits_cpu }}"
              memory: "{{ .Values.data.limits_memory }}"
      serviceAccountName: "{{ .Values.data.serviceAccountName }}"
