apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.conf.appName }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  hosts:
    - "*"
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            prefix: "/api/partition"
      route:
        - destination:
            port:
              number: 80
            host: "{{ .Values.conf.appName }}.{{ .Release.Namespace }}.svc.cluster.local"
