{{- if .Values.conf.istioEnabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  hosts:
    {{- if and .Values.conf.domain .Values.conf.onPremEnabled }}
    - {{ printf "osdu.%s" .Values.conf.domain | quote }}
    {{- else if .Values.conf.domain }}
    - {{ .Values.conf.domain | quote }}
    {{- else }}
    - "*"
    {{- end }}
  gateways:
    - service-gateway
  http:
    {{- if .Values.conf.publicAvailable }}
    - match:
        - uri:
            prefix: "/api/partition"
    {{- else }}
    - match:
        - uri:
            exact: "/api/partition/v1/info"
    {{- end }}
      route:
        - destination:
            port:
              number: 80
            host: {{ printf "%s.%s.svc.cluster.local" .Values.conf.appName .Release.Namespace | quote }}
{{- end }}
