apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  GOOGLE_CLOUD_PROJECT: "{{ .Values.data.google_cloud_project }}"
  PARTITION_ADMIN_ACCOUNT: "{{ .Values.data.partition_admin_account }}"
  GOOGLE_AUDIENCES: "{{ .Values.data.google_audiences }}"
  KEY_RING: "{{ .Values.data.key_ring }}"
  LOG_LEVEL: "{{ .Values.data.log_level }}"
