apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  GOOGLE_CLOUD_PROJECT: "{{ .Values.data.google_cloud_project }}"
  PARTITION_ADMIN_ACCOUNTS: "{{ .Values.data.partition_admin_accounts }}"
  GOOGLE_AUDIENCES: "{{ .Values.data.google_audiences }}"
  LOG_LEVEL: "{{ .Values.data.log_level }}"
  SERVICE_ACCOUNT_TAIL: "{{ .Values.data.service_account_tail }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.data.spring_profiles_active }}"
