global:
  domain: ""
  limitsEnabled: true
  dataPartitionId: ""
  logLevel: "ERROR"
  tier: ""
  autoscalingMode: "cpu"

data:
  # configmaps
  logLevel: ""
  # deployments
  requestsCpu: "50m"
  requestsMemory: "350Mi"
  limitsCpu: "500m"
  limitsMemory: "1G"
  serviceAccountName: "partition"
  imagePullPolicy: "IfNotPresent"
  image: "community.opengroup.org:5555/osdu/platform/system/partition/osdu-gcp-partition-quarkus:latest"
  affinityLabelsSpot:
    cloud.google.com/gke-provisioning:
      - spot
  affinityLabelsStandard:
    cloud.google.com/gke-provisioning:
      - standard
  systemPartitionConfigPath: "/mnt/system-partition"
  dataPartitionsConfigPath: "/mnt/data-partitions"
  # data partition configuration
  projectId: ""
  tenantServiceAccount: ""
  operatorMode: "prod"
  databaseId: "osdu-system"
  elasticHttps: true
  indexerAugmenterEnabled: true
  policyServiceEnabled: true
  edsEnabled: false
  autoCompleteEnabled: true
  asIngestedCoordinatesEnabled: true
  keyWordLowerEnabled: true
  bagOfWordsEnabled: true
  xCollaborationEnabled: false
  partitionProperties:
    properties: {}
    # example of custom property
    # - name: foo
    #   sensitive: false
    #   value: bar

conf:
  appName: "partition-quarkus"
  configmap: "partition-quarkus-config"
  configmapPartitions: "quarkus-partitions"
  replicas: 1

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "5m"
  bootstrapProxyCPULimit: "100m"
  sidecarInject: "true"
  partitionEditors: []

hpa:
  minReplicas: 1
  maxReplicas: 6
  cpu:
    utilization: 300
    scaleUpStabilizationWindowSeconds: 30
    scaleUpValue: 200
    scaleUpPeriod: 15
    scaleDownStabilizationWindowSeconds: 150
    scaleDownValue: 100
    scaleDownPeriod: 15
  requests:
    targetType: "AverageValue"
    targetValue: 400
    scaleUpStabilizationWindowSeconds: 10
    scaleUpValue: 50
    scaleUpPeriod: 15
    scaleDownStabilizationWindowSeconds: 60
    scaleDownValue: 25
    scaleDownPeriod: 60

limits:
  maxTokens: 300
  tokensPerFill: 300
  fillInterval: "1s"
